from .turbulence_heating_vazza_data2d_return_model import TurbulenceHeatingVazzaData2dReturnModel
from .turbulence_heating_vazza_data3d_return_model import TurbulenceHeatingVazzaData3dReturnModel
from .turbulence_heating_vazza_calculation_info_model import TurbulenceHeatingVazzaCalculationInfoModel