from .turbulence_heating_vazza_time_series_calculation_info_model import (
    TurbulenceHeatingVazzaTimeSeriesCalculationInfoModel
)
from .turbulence_heating_vazza_profile_calculation_info_model import (
    TurbulenceHeatingVazzaProfileCalculationInfoModel
)